apiVersion: v1
kind: Service
metadata:
  name: {{ include "static-site.name" . }}
spec:
  selector:
    app: {{ include "static-site.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
