apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec/preserveUnknownFields
  sources:
  - repoURL: https://helm.nginx.com/stable
    chart: nginx-ingress
    targetRevision: 1.4.0
    helm:
      valueFiles:
      - $values/nginx-ingress/values.yaml
  - repoURL: https://github.com/dorilahav/k8s-apps.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ingress
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
